#!/bin/sh

#
# This simple script lists out the current pkgs git repos to a file. 
# This speeds up cgit as it doesn't have to recurse into all dirs 
# Looking for git repos. 
#

eval "$(crudini --format=sh --get /etc/dist-git/dist-git.conf)"
destination=$gitroot_dir/pkgs-git-repos-list

if [ -n "$1" ]
then
  destination=$1
fi

newfile=`mktemp`

cd $gitroot_dir/repositories
ls > $newfile
cp -fZ $newfile $destination
rm $newfile
#chown apache:apache $destination
chmod 644 $destination
