# See the documentation for more information:
# https://packit.dev/docs/configuration/
---
upstream_project_url: https://github.com/release-engineering/dist-git

actions: &common_actions
  create-archive:
    - bash -c "tito build --tgz --test -o ."
    - bash -c "ls -1t ./*.tar.gz | head -n 1"
  get-current-version:
    - bash -c "grep -Po 'Version. +\K.*' *.spec"

srpm_build_deps:
  - tito
  - git

packages:
  dist-git:
    specfile_path: dist-git.spec
    upstream_package_name: dist-git
    downstream_package_name: dist-git
    upstream_tag_template: 'dist-git-{version}'
    paths:
      - dist-git
  dist-git-client:
    specfile_path: dist-git-client.spec
    upstream_package_name: dist-git-client
    downstream_package_name: dist-git-client
    upstream_tag_template: 'dist-git-client-{version}'
    paths:
      - dist-git-client
jobs:
  - &copr
    job: copr_build
    packages:
      - dist-git
      - dist-git-client
    trigger: pull_request
    metadata:
      targets:
        - fedora-all-x86_64
        - epel-8-x86_64
        - epel-9-x86_64
        - epel-10-x86_64

  - <<: *copr
    trigger: commit
    metadata:
      owner: "@copr"
      project: "copr-dev"
      branch: main
